root: true
parserOptions:
  ecmaVersion: 2019
  sourceType: "module"
  ecmaFeatures:
    jsx: true
extends:
  - eslint:recommended
  - plugin:react/recommended
settings:
  react:
    version: "16.5.2"
env:
  browser: true,
  es6: true
rules:
  react/react-in-jsx-scope: off
  react/prop-types: off
